/* Averages */
SELECT AVG(POPULATION) FROM CITY WHERE DISTRICT='California';

/* Sum Function */
SELECT SUM(POPULATION) FROM CITY WHERE DISTRICT='California';

/* Count Function */
SELECT COUNT(ID) FROM CITY WHERE POPULATION > 100000;
