/* Weather Observation 1 */
SELECT CITY, STATE FROM STATION;

/* Weather Observation 2 */
SELECT ROUND(SUM(LAT_N),2), ROUND(SUM(LONG_W),2) FROM STATION;

/* Weather Observation 3 */
SELECT DISTINCT CITY FROM STATION WHERE ID%2=0;

/* Weather Observation 4 */
SELECT COUNT(CITY) - COUNT(DISTINCT CITY) FROM STATION;

/* Weather Observation 5 */
SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) ASC, CITY LIMIT 1;
SELECT CITY, LENGTH(CITY) FROM STATION ORDER BY LENGTH(CITY) DESC, CITY LIMIT 1;

/* Weather Observation 6 */
SELECT DISTINCT CITY FROM STATION WHERE LEFT(CITY, 1) IN ('A','E','I','O','U');

/* Weather Observation 7 */
SELECT DISTINCT CITY FROM STATION WHERE RIGHT(CITY, 1) IN ('A','E','I','O','U');

/* Weather Observation 8 */
SELECT DISTINCT CITY FROM STATION WHERE LEFT(CITY, 1) IN ('A','E','I','O','U') AND RIGHT(CITY, 1) IN ('A','E','I','O','U');

/* Weather Observation 9 */
SELECT DISTINCT CITY FROM STATION WHERE LEFT(CITY, 1) NOT IN ('A','E','I','O','U');

/* Weather Observation 10 */
SELECT DISTINCT CITY FROM STATION WHERE RIGHT(CITY, 1) NOT IN ('A','E','I','O','U');

/* Weather Observation 11 */
SELECT DISTINCT CITY FROM STATION WHERE LEFT(CITY, 1) NOT IN ('A','E','I','O','U') OR RIGHT(CITY, 1) NOT IN ('A','E','I','O','U');

/* Weather Observation 12 */
SELECT DISTINCT CITY FROM STATION WHERE LEFT(CITY, 1) NOT IN ('A','E','I','O','U') AND RIGHT(CITY, 1) NOT IN ('A','E','I','O','U');

/* Weather Observation 13 */
SELECT ROUND(SUM(LAT_N),4) FROM STATION WHERE LAT_N > 38.7880 AND LAT_N < 137.2345;

/* Weather Observation 14 */
SELECT ROUND(MAX(LAT_N),4) FROM STATION WHERE LAT_N < 137.2345;

/* Weather Observation 15 */
SELECT ROUND(LONG_W,4) FROM STATION WHERE LAT_N = (SELECT MAX(LAT_N) FROM STATION WHERE LAT_N < 137.2345);

/* Weather Observation 16 */
SELECT ROUND(MIN(LAT_N),4) FROM STATION WHERE LAT_N > 38.7780;

/* Weather Observation 17 */
SELECT ROUND(LONG_W,4) FROM STATION WHERE LAT_N = (SELECT MIN(LAT_N) FROM STATION WHERE LAT_N > 38.7780);

/* Weather Observation 18 */
SELECT ROUND(ABS(MAX(LAT_N) - MIN(LAT_N)) + ABS(MAX(LONG_W) - MIN(LONG_W)),4) FROM STATION;

/* Weather Observation 19 */
SELECT ROUND(SQRT(POWER(MAX(LAT_N) - MIN(LAT_N),2) + POWER(MAX(LONG_W) - MIN(LONG_W),2)),4) FROM STATION;

/** Weather Observation 20 */
SELECT ROUND(LAT_N,4) FROM (SELECT LAT_N, ROW_NUMBER() OVER(ORDER BY LAT_N ASC) AS row_num, (SELECT COUNT(*) FROM STATION) AS total_count FROM STATION ) sub_table WHERE row_num = (total_count+1)/2;
/*sub_table --> alias = nome alternativo para coluna ou tabela
+1 -> se tiver 1 coluna /2*/
